### ISSUE TITLE
Notice: Undefined index: categories

### ISSUE THREAD

**Issue by AreSee** [MdnAgency/prestashop-mdn_blocks#1]
![error](https://user-images.githubusercontent.com/78718567/219957713-6309e0d8-6d03-464f-96c5-43735ba55bac.JPG)

PS 1.7.8.8
PHP: 7.4-fpm

Fix error with 
`    public function postProcess() {
		if(isset($_POST['categories'])) {
			$_POST['categories'] = implode(",", $_POST['categories']);
		}
       // die();
        parent::postProcess();
    }`

in controllers/admin/AdminBlockCategoryController.php Line 32?

**Comment by DevLoris** [comment]
Hi ! 
Thanks for the report, the issue is now resolved !
